### PR TITLE
#854 - Proxy entries for annotations on interface not created

### PR DESCRIPTION
**Pull request by phejl**

### CODE REVIEW

**Review by aclement — APPROVED** [review]
It looks ok. unit tests are fine but I do find tweaking an existing sample so that it actually needs your code to work properly is a good way to get a positive feeling that it'll behave in a native-image.

**Comment by aclement** [comment]
I merged it.

**Comment by sdeleuze** [comment]
@phejl Thanks for your contributions and feel free to create PRs without related issue, we can set PR milestone and they will be visible in the changelog.

**Comment by phejl** [comment]
@sdeleuze Thank you. Noted.

**Pull request closed without merging**
