### PR TITLE
Introduces profiles for building with different databases.

### PR DESCRIPTION
**Pull request by schauder**
To run the build with hsqldb:
```
export DB=hsqldb
./build.sh
```

### CODE REVIEW

**Comment by sdeleuze** [comment]
@schauder Could you please update the related `build.sh` in one of the data samples to test the drivers supported by those profiles?

**Comment by schauder** [comment]
So It should run the test for all available profiles?

**Comment by sdeleuze** [comment]
Yes I think so.

**Comment by schauder** [comment]
> @schauder Could you please update the related `build.sh` in one of the data samples to test the drivers supported by those profiles?

Done.

**Pull request merged**
