### PR TITLE
Transition JpaComponentProcessor to BeanFactoryNativeConfigurationProcessor

### PR DESCRIPTION
**Pull request by christophstrobl**
Replace the `JpaComponentProcessor` with a `BeanFactoryNativeConfigurationProcessor` implementation.

Resolves: #1208

### CODE REVIEW

**Review by sdeleuze — CHANGES_REQUESTED** [review]
I tested this PR locally, I see a lot of logs from `org.springframework.data.JpaConfigurationProcessor` and very slow test execution when running `./build.sh` at the root. Could you please double check if something need to be refined?

**Comment by christophstrobl** [comment]
This might be caused by multiple scans of the path to looking for types annotated with `javax.persistence.Entity`.

**Comment by sdeleuze** [comment]
Just when running tests it seemed to be significantly pretty slow, so I am wondering if an optimization could be done to avoid too much performance impact.

**Comment by sdeleuze** [comment]
Merged thanks!

**Pull request closed without merging**
