### PR TITLE
Add codeGenDebugPort property to debug Spring AOT plugins

### PR DESCRIPTION
**Pull request by ttddyy**
When this parameter is present, launch the code gen process with remote debug mode.

Sample command:
```
> mvn -Pnative spring-aot:generate@generate -Dspring.aot.codeGenDebugPort=9000
```

### CODE REVIEW

**Review by sdeleuze — CHANGES_REQUESTED** [review]
Thanks a lot for this very interesting PR, any chance you could fix the typo and do the same on Grade side + add related documentation?

**Comment by wilkinsona** [comment]
On the Gradle side, given that `GenerateAotSources` is already a `JavaExec` subclass, I wonder if it would be better to lean on its existing [debug options](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/JavaExec.html#debugOptions-org.gradle.api.Action-) for this, to some extent at least.

**Comment by sdeleuze** [comment]
@wilkinsona Thanks for your feedback, could you explore this proposal @ttddyy ?

**Comment by sdeleuze** [comment]
Given the fact we deeply need AOT debugging capabilities to move forward I will merge this PR as it is, and will create a related issue to implement @wilkinsona proposal.

**Comment by ttddyy** [comment]
Thanks @wilkinsona  I'm still learning the gradle side, so appreciated the guidance.
I will address it and documentation in the new issue(#978)

**Pull request merged**
