### PR TITLE
Remove json files for config-client-new

### PR DESCRIPTION
**Pull request by spencergibb**
Fixes gh-354

/cc @ryanjbaxter @aclement

### CODE REVIEW

**Comment by sdeleuze** [comment]
I don't see additional hints in this PR, maybe you have them locally?

**Comment by spencergibb** [comment]
So far, for config client new it didn't need them. Config client likely will.

**Comment by sdeleuze** [comment]
I did a quick test, with the native config `config-client-new` is green, if I remove the `META-INF/native-image` directory and then run `build-without-server-build.sh` it fails. Could you please double check?

**Comment by spencergibb** [comment]
You have to do `./build.sh` the first time. Only then, can you call `build-without-server-build.sh`

**Comment by sdeleuze** [comment]
Yeah that's what I did and `build-without-server-build.sh` failed.

**Comment by spencergibb** [comment]
You'll notice I also made a change to the sample app itself

**Comment by aclement** [comment]
I've fixed the problem that necessitated changing the client app - either should work (separate commandlinerunner or simple bean). And can confirm deleting the config for the '-new' variant leaves you with a working app now.

**Comment by spencergibb** [comment]
Closing due to the move of the samples directory.

**Pull request closed without merging**
