### PR TITLE
Auditing Support for Spring Data

### LINKED ISSUE #860: Runtime exception when setting @EnableR2dbcAuditing
Hi!
When I set the annotation @EnableR2dbcAuditing（WebFlux + R2DBC）, I have the following exception at runtime. When the annotation is commented out, I am able to run successfully the docker native container.

Thanks!

JAVA11
GraalVM 21.1.0.

```
2021-06-24 09:42:15.989  WARN 1 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: E
rror creating bean with name 'wechatRepository' defined in com.mcmcnet.micro.repository.WechatRepository defined in @EnableR2dbcRepositories declared on MicroOperationApplication: Cannot resolve reference to bean 'r2dbcEntityTemplate' wh
ile setting bean property 'entityOperations'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcEntityTemplate' defined in class path resource [org/springframework/boot/autoc
onfigure/data/r2dbc/R2dbcDataAutoConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.data.r2dbc.mapping.even
t.ReactiveAuditingEntityCallback': Cannot create inner bean '(inner bean)#336dc1b6' of type [org.springframework.beans.factory.config.ObjectFactoryCreatingFactoryBean] while setting constructor argument; nested exception is org.springfra
mework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#336dc1b6': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springf
ramework.beans.factory.config.ObjectFactoryCreatingFactoryBean]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.beans.factory.config.ObjectFactoryCreatingFactoryBean.<init>()

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-06-24 09:42:16.000 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for org.springframework.beans.factory.config.ObjectFactoryCreatingFactoryBean.<init>() is missing.

Action:

Native configuration for a method accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.
```

### LINKED ISSUE #882: Spring Data Audit Not Working Even After 0.10.1
This still doesn't work in 0.10.1, even after the support for @Transactional and @Async was added w/ the Class Proxy hints.

Here is a sample project:

https://github.com/matthenry87/native-spring-data-auditing

```
Could not configure Spring Data JPA auditing-feature because spring-aspects.jar is not on the classpath!
If you want to use auditing please add spring-aspects.jar to the classpath.
2021-06-29 03:18:29.044  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-06-29 03:18:29.045 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: org.springframework.beans.factory.aspectj.AnnotationBeanConfigurerAspect not found.
Could not configure Spring Data JPA auditing-feature because spring-aspects.jar is not on the classpath!
If you want to use auditing please add spring-aspects.jar to the classpath.
        at org.springframework.data.jpa.repository.config.JpaAuditingRegistrar.registerBeanConfigurerAspectIfNecessary(JpaAuditingRegistrar.java:125) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.data.jpa.repository.config.JpaAuditingRegistrar.registerBeanDefinitions(JpaAuditingRegistrar.java:88) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:5.3.8]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396) ~[na:na]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:395) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:157) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:5.3.8]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:5.3.8]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication.main(NativeSpringDataAuditingApplication.java:31) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:na]

### PR DESCRIPTION
**Pull request by schauder**
Closes #860
Closes #882

### CODE REVIEW

**Review by christophstrobl — CHANGES_REQUESTED** [review]
Can we move the common parts of the hints to a dedicated class and pull them in via `imports`.

Thinking about the types from commons like  `IsNewAwareAuditingHandler`, `LazyInitTargetSource` and the proxy configuration.

Would help us with the other data modules.

**Comment by schauder** [comment]
> Can we move the common parts of the hints to a dedicated class and pull them in via `imports`.

That's my plan with the next modules, which I want to tackle today.
Sticking to the rule of refactoring, when you have three repetitions.

**Comment by sdeleuze** [comment]
Ok so I will wait for those changes before merging.

**Comment by schauder** [comment]
With the additional commits we also support Auditing for Elasticsearch. And they include the refactoring to exract common hints to a single place.

**Comment by schauder** [comment]
This PR now adds Auditing support for all Spring Data samples.

**Comment by christophstrobl** [comment]
@schauder could you please add license headers to the newly introduced files.

**Comment by schauder** [comment]
> @schauder could you please add license headers to the newly introduced files.

@christophstrobl done.

**Review by christophstrobl — APPROVED** [review]
LGTM

**Pull request merged**
