### PR TITLE
Switch sample to Spring Integration 5.5.6-SNAPSHOT

### PR DESCRIPTION
**Pull request by artembilan**
Fixes https://github.com/spring-projects-experimental/spring-native/issues/1155
Related to https://github.com/spring-projects-experimental/spring-native/issues/1134

The `FactoryBean.OBJECT_TYPE_ATTRIBUTE` is crucial for those `FactoryBean` impls
which does not expose the target type during compilation.

* Add `FactoryBean.OBJECT_TYPE_ATTRIBUTE` as a candidate for the
`DefaultBeanRegistrationWriter.getAttributeFilter()` since that one is `false` by default anyway
* Rework `IntegrationApplication` to reflect the current Spring Boot state
* Use `spring-integration-5.5.6-SNAPSHOT` for the latest bean definition changes over there

The `build.sh -a` now passes for the integration sample.
Cannot confirm in the native mode since GraalVM doesn't work well on Windows: too long command line.
Need to build classpath file (jar with respective META-INF) somehow...

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks Artem. With your help I was able to move further and inspect the problematic bean definition. I can see that the bean definition for the `integrationApplication$ControlBusGateway` has a `FactoryBean.OBJECT_TYPE_ATTRIBUTE` but it doesn't seem to have the right type to me and I am wondering why writing it back works the way it does.

AFAIK this attribute should either be a `Class` or a `ResolvableType`. Any other type is ignored so I guess the current `org.springframework.beans.BeanMetadataAttribute` is converted somewhere to a class. This explains why me checking for the attribute didn't work as I didn't expect such a type.

**Comment by snicoll** [comment]
> Cannot confirm in the native mode since GraalVM doesn't work well on Windows: too long command line.
Need to build classpath file (jar with respective META-INF) somehow...

It does not work but I am making progress:

```Error creating bean with name 'webFluxIntegrationRequestMappingHandlerMapping': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'order' of bean class [org.springframework.integration.webflux.inbound.WebFluxIntegrationRequestMappingHandlerMapping]: Bean property 'order' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?```

**Comment by snicoll** [comment]
So the problem here is that we don't call `BeanDefinitionRegistryPostProcessor` that are defined as bean definitions. It's a tricky problem because if we did, we should remove the bean definition for it without any guarantee whatsoever that the bean is not used for other purposes. 

What's happening now is that a BDRPP defined in Spring Integration is invoked at runtime, and create the `webFluxIntegrationRequestMappingHandlerMapping` bean definition only at runtime which has not been procssed for native use.

**Comment by artembilan** [comment]
Thanks, Stephane, for feedback!
I wish I could run GraalVM build on my Windows to see these problems myself...

Nevertheless. Spring Integration has only this `BDRPP` - `IntegrationConfigurationBeanFactoryPostProcessor`, which is registered only once when an `@EnableIntegration` is processed.
That one does this logic:
```
List<IntegrationConfigurationInitializer> initializers =
				SpringFactoriesLoader.loadFactories(IntegrationConfigurationInitializer.class,
						beanFactory.getBeanClassLoader());

for (IntegrationConfigurationInitializer initializer : initializers) {
	initializer.initialize(beanFactory);
}
```

So, yes, it is indeed a programmatic bean definition registrations.

I guess, I'll revise my `IntegrationConfigurationInitializer` implementations in favor of just `instanceSupplier` (no `addPropertyValue()` or so), which is still supported in Native runtime I guess.

**Comment by snicoll** [comment]
There's no need to do anything Artem. I am working on this already and have made progress, see https://github.com/spring-projects-experimental/spring-native/issues/1213

**Pull request closed without merging**
